### ISSUE TITLE
Volume creation failure raises error

### ISSUE THREAD

**Issue by emiran-orange** [Excelero/nvmesh-csi-driver#37]
Now that #35 is fixed, volume creation failures not involving disabling the zone cause a stack trace:
```
CSIDriver - ERROR - Error caught in gRPC call  CreateVolume - 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/driver/common.py", line 60, in func_wrapper
    return func(self, request, context)
  File "/driver/controller_service.py", line 65, in CreateVolume
    csiVolume = self.do_create_volume(log, nvmesh_vol_name, request)
  File "/driver/controller_service.py", line 90, in do_create_volume
    zone = self.create_volume_on_a_valid_zone(volume, allowed_zones, log)
  File "/driver/controller_service.py", line 116, in create_volume_on_a_valid_zone
    self.create_volume_in_zone(volume, selected_zone, log)
  File "/driver/controller_service.py", line 147, in create_volume_in_zone
    self._handle_create_volume_errors(err, data, volume, zone, mgmt_server, log)
  File "/driver/controller_service.py", line 165, in _handle_create_volume_errors
    volume_already_exists = 'Name already Exists' in data[0]['error'] or 'duplicate key error' in json.dumps(data[0]['error'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```
I dumped the data and err vars:
data: `None`
err: 
`{'content': 'Received incorrect REST request! Error: data.body[0].capacity should be >= 1000000000, data.body[0].capacity should be equal to constant, data.body[0].capacity should be equal to constant, data.body[0].capacity should match some schema in anyOf, data.body should match "then" schema', 'message': 'Unprocessable Entity', 'code': 422}`

**Comment by gil-excelero** [comment]
Fixed in 20a81d5f47a626f546af529fbc9590c5a3ab5d32
